# Generated by Django 4.2.1 on 2023-09-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_deviceassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceassignment',
            name='condition',
            field=models.CharField(default='Good', max_length=255),
        ),
    ]
