# Generated by Django 4.2.1 on 2023-09-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_remove_devicelog_condition_at_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceassignment',
            name='device_log',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
