# Generated by Django 4.2.1 on 2023-09-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_deviceassignment_device_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceassignment',
            name='device_log',
        ),
        migrations.AddField(
            model_name='device',
            name='device_log',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DeviceLog',
        ),
    ]
