# Generated by Django 4.2.1 on 2023-09-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_remove_deviceassignment_device_log_device_device_log_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='condition',
            new_name='condition_at_checkout',
        ),
        migrations.AddField(
            model_name='device',
            name='condition_at_return',
            field=models.CharField(default='Good', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_log',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
