# Generated by Django 4.2.1 on 2023-09-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_rename_condition_device_condition_at_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='condition_at_return',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
