# Generated by Django 4.2.1 on 2023-09-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_alter_device_condition_at_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='condition_at_return',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
