# Generated by Django 4.2.1 on 2023-09-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_alter_device_condition_at_return'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceassignment',
            old_name='condition',
            new_name='condition_at_checkout',
        ),
        migrations.RemoveField(
            model_name='device',
            name='condition_at_checkout',
        ),
        migrations.RemoveField(
            model_name='device',
            name='condition_at_return',
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='condition_at_return',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
