# Generated by Django 4.2.1 on 2023-09-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('employee', '0002_alter_employee_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='devices',
            field=models.ManyToManyField(blank=True, to='device.device'),
        ),
    ]
