# Generated by Django 4.2.1 on 2023-09-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='devices',
        ),
    ]
